---
abstract: 'Perl interface to Public Transport Victoria (PTV) Website.'
author:
  - 'Luke Poskitt <ltp@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-PTV
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TreeBuilder: 0
  LWP: 0
  Test::More: 0
  WWW::Mechanize: 0
version: 0.05
